import type { Metadata } from "next";
import "../../default_shadcn_theme.css";
import "./../styles/index.css";
import "./../styles/fonts.css";
import "./../styles/tailwind.css";
import "./../styles/theme.css";

import Sidebar from "./components/Sidebar";
import AIChatbot from "./components/AIChatbot";
import { ThemeProvider } from "./components/ThemeProvider";

export const metadata: Metadata = {
  title: "Design Midnight SaaS Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
